// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALc02imEz759RuCYZ2OcQ1ZS9ZbHvRqD0',
    appId: '1:335877243346:web:2192d73ad16b19a293880b',
    messagingSenderId: '335877243346',
    projectId: 'e-commerce-test-app-af433',
    authDomain: 'e-commerce-test-app-af433.firebaseapp.com',
    storageBucket: 'e-commerce-test-app-af433.firebasestorage.app',
    measurementId: 'G-CZM20JJ014',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAblFrrURyMBsJqinTsqJdwYUOlAFlyCBM',
    appId: '1:335877243346:android:802be0cb30ab05f993880b',
    messagingSenderId: '335877243346',
    projectId: 'e-commerce-test-app-af433',
    storageBucket: 'e-commerce-test-app-af433.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSoTIt4-jw9v5Q-hiUz58jJVwj-bo7-II',
    appId: '1:335877243346:ios:c7287756938e597e93880b',
    messagingSenderId: '335877243346',
    projectId: 'e-commerce-test-app-af433',
    storageBucket: 'e-commerce-test-app-af433.firebasestorage.app',
    iosBundleId: 'com.example.base',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSoTIt4-jw9v5Q-hiUz58jJVwj-bo7-II',
    appId: '1:335877243346:ios:c7287756938e597e93880b',
    messagingSenderId: '335877243346',
    projectId: 'e-commerce-test-app-af433',
    storageBucket: 'e-commerce-test-app-af433.firebasestorage.app',
    iosBundleId: 'com.example.base',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALc02imEz759RuCYZ2OcQ1ZS9ZbHvRqD0',
    appId: '1:335877243346:web:3d9ee56f60c4d49e93880b',
    messagingSenderId: '335877243346',
    projectId: 'e-commerce-test-app-af433',
    authDomain: 'e-commerce-test-app-af433.firebaseapp.com',
    storageBucket: 'e-commerce-test-app-af433.firebasestorage.app',
    measurementId: 'G-53W2MBKM1R',
  );
}
